ACS-1220-Auth-Lab-main/books_app/main/routes.py
"""Import packages and modules."""
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from books_app.models import Book, Author, Genre, User
from books_app.main.forms import BookForm, AuthorForm, GenreForm

# Import app and db from events_app package so that we can run app
from books_app.extensions import app, bcrypt, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    all_books = Book.query.all()
    all_users = User.query.all()
    return render_template('home.html', 
        all_books=all_books, all_users=all_users)


@main.route('/create_book', methods=['GET', 'POST'])
@login_required
def create_book():
    form = BookForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_book = Book(
            title=form.title.data,
            publish_date=form.publish_date.data,
            author=form.author.data,
            audience=form.audience.data,
            genres=form.genres.data
        )
        db.session.add(new_book)
        db.session.commit()

        flash('New book was created successfully.')
        return redirect(url_for('main.book_detail', book_id=new_book.id))
    return render_template('create_book.html', form=form)


@main.route('/create_author', methods=['GET', 'POST'])
@login_required
def create_author():
    # TODO: Make an AuthorForm instance

    # TODO: If the form was submitted and is valid, create a new Author object
    # and save to the database, then flash a success message to the user and
    # redirect to the homepage

    # TODO: Send the form object to the template, and use it to render the form
    # fields
    return render_template('create_author.html')


@main.route('/create_genre', methods=['GET', 'POST'])
@login_required
def create_genre():
    # TODO: Make a GenreForm instance

    # TODO: If the form was submitted and is valid, create a new Genre object
    # and save to the database, then flash a success message to the user and
    # redirect to the homepage

    # TODO: Send the form object to the template, and use it to render the form
    # fields
    return render_template('create_genre.html')


@main.route('/book/<book_id>', methods=['GET', 'POST'])
def book_detail(book_id):
    book = Book.query.get(book_id)
    form = BookForm(obj=book)

    # TODO: If the form was submitted and is valid, update the fields in the 
    # Book object and save to the database, then flash a success message to the 
    # user and redirect to the book detail page

    return render_template('book_detail.html', book=book, form=form)


@main.route('/profile/<username>')
def profile(username):
    # TODO: Make a query for the user with the given username, and send to the
    # template

    # STRETCH CHALLENGE: Add ability to modify a user's username or favorite 
    # books
    return render_template('profile.html', username=username)


# TODO: Add `@login_required`
@main.route('/favorite/<book_id>', methods=['POST'])
def favorite_book(book_id):
    book = Book.query.get(book_id)
    # TODO: If the book is not already in user's favorites, then add it,
    # commit the change to the database, and flash a success message.
    # if User.query.get(favorite_book=) is None:
    if not current_user.favorite_books.includes(book):
        current_user.favorite_books.append(book)
        db.session.commit()
        flash('Book added as a favorite!')

    # Then, redirect the user to the book detail page for the given book.
    return render_template('book_detail.html', book=book)


# TODO: Add `@login_required`
@main.route('/unfavorite/<book_id>', methods=['POST'])
def unfavorite_book(book_id):
    # TODO: If the book is in user's favorites, then remove it,
    # commit the change to the database, and flash a success message.

    # Then, redirect the user to the book detail page for the given book.
    return "Not yet implemented!"

ACS-1220-Auth-Lab-main/books_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Book Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            <nav>
                <a href="/">Home</a>
                <div>
                    <!-- TODO: Only show these links if the current user is 
                        authenticated (logged in)! -->
                    {% if current_user.is_authenticated %}
                    <a href="/create_book">Create Book</a>
                    <a href="/create_author">Create Author</a>
                    <a href="/create_genre">Create Genre</a>
                    <a href="/logout">Log Out</a>

                    <!-- TODO: Only show these links if the current user is NOT
                        authenticated (logged in)! -->
                    {% else %}
                    <a href="/signup">Sign Up</a>
                    <a href="/login">Log In</a>
                    {% endif %}
                </div>
            </nav>

            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}

            {% if current_user.is_authenticated %}
            <p>You are logged in as {{ current_user.username }}</p>
            {% endif %}

            {% block content %}{% endblock %}
        </div>
    </body>
</html>

ACS-1220-Auth-Lab-main/books_app/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>

<!-- TODO: Show this only if the user is logged in and the book is not in their 
    favorites-->
<!-- {% if current_user.is_authenticated  && book.id is not in current_user.favorite_books %} -->
<form action="/favorite/{{ book.id }}" method="POST">
    <input type="submit" value="Favorite This Book">
</form>


<!-- TODO: Show this only if the user is logged in and the book is not in their 
    favorites-->
<form action="/unfavorite/{{ book.id }}" method="POST">
    <input type="submit" value="Unfavorite This Book">
</form>

<p>
    <strong>Author</strong>: {{ book.author.name }}
</p>

<p>
    <strong>Author Bio</strong>: {{ book.author.biography }}
</p>

<p>
    <strong>Publish date</strong>: {{ book.publish_date }}
</p>

<p>
    <strong>Audience</strong>: {{ book.audience }}
</p>

<p>
    <strong>Genres</strong>: 
    
    {% for genre in book.genres %}
    {{ genre.name }},
    {% endfor %}
</p>

<form method="POST" action="{{ url_for('main.book_detail', book_id=book.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit this book</legend>

        {{ form.title.label }}
        {{ form.title }}
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        
        {{ form.author.label }}
        {{ form.author }}
        
        {{ form.audience.label }}
        {{ form.audience }}
        
        {{ form.genres.label }}
        {{ form.genres }}
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/create_author.html
{% extends 'base.html' %}

{% block content %}

<p>Author creation form.</p>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->

{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/create_book.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_book') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a book</legend>

        {{ form.title.label }}
        {{ form.title }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.author.label }}
        {{ form.author }}
        <ul>
        {% for error in form.author.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.audience.label }}
        {{ form.audience }}
        <ul>
        {% for error in form.audience.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.genres.label }}
        {{ form.genres }}
        <ul>
        {% for error in form.genres.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/create_genre.html
{% extends 'base.html' %}

{% block content %}

<p>Genre creation form.</p>

<!-- TODO: Add a <form> element here and use the form variable to show the labels & fields -->

{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Books</h2>

<ul>
{% for book in all_books %}
    <li><a href="/book/{{ book.id }}">{{ book.title }}</a> by {{ book.author.name }}</li>
{% endfor %}
</ul>

<h2>Users</h2>

<p>
    <a href="/create_user">+ New User</a>
</p>

<ul>
    {% for user in all_users %}
        <li><a href="/profile/{{ user.username }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>



{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>
<!-- TODO: Fill in the sign up form here! -->
<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<p>
Welcome to {{ username }}'s profile.
</p>

<!-- TODO: Display the user's actual favorites here -->

<p>
    {{ username }}'s favorite books are:

    <ul>
        <li>Your</li>
        <li>Favorites</li>
        <li>Go</li>
        <li>Here</li>
    </ul>
</p>

{% endblock %}

ACS-1220-Auth-Lab-main/books_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>
<!-- TODO: Fill in the sign up form here! -->
<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}